---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  download_results: /tmp/report

platforms:
- name: cpan-mirror-berkshelf
  driver_config:
    box: ubuntu-13.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box
  run_list:
  - recipe[cpan-mirror]
  attributes:
    cpan_mirror:
      data_dir: /home/vagrant/cpan
      user: vagrant

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[cpan-mirror-test]
  attributes:
    minitest:
      ci_reports: /tmp/report
